server:
  port: 8801
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: master
    port: 5672
    username: chris
    password: 123456
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于binding整合
          type: rabbit #消息组件类型
      bindings: #服务的整合处理
        output: #一个通道的名称
          destination: studyExchange #要使用的Exchange的名称
          content-type: application/json #设置消息类型，文本设置为 text/plain]
          binder: defaultRabbit

eureka:
  client:
    # 表示是否将自己注册到eureka-server,默认为true
    register-with-eureka: true
    # 是否从eureka-server抓取自己的注册信息，默认为true，单节点无所谓，集群必需设置为true以配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: stream-provider8801
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端收到客户端最后一次心跳后等待的时间上限，超时将注销服务，默认为90秒
    lease-expiration-duration-in-seconds: 2