server:
  port: 8006
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: master
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/actuator/health
        #默认10s
        health-check-interval: 3s
