server:
  port: 8002
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.1.20:3306/dg?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    ## 张奇隆电脑上的mysql
    url: jdbc:mysql://192.168.140.127:3306/chris?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 65536
    druid:
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #当数据库抛出不可恢复的异常时,抛弃该连接
      #exception-sorter: true
      #是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #配置扩展插件
      filters: stat,wall,slf4j,config
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        login-username: admin
        login-password: allsale
      filter:
        wall:
          config:
            comment-allow: true
          enabled: true

#  redis:
#    host: master
#    password: 123456
#    port: 6379
#    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #所有Entity别名类所在包
  type-aliases-package: com.chris.springcloud.entities

#  mybatis-plus:
#    mapper-locations: classpath:mappers/*.xml
#    global-config:
#      db-config:
#        #驼峰下划线转换
#        #column-underline: true
#        #逻辑删除配置
#        logic-delete-value: I
#        logic-not-delete-value: A
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    # 表示是否将自己注册到eureka-server,默认为true
    register-with-eureka: true
    # 是否从eureka-server抓取自己的注册信息，默认为true，单节点无所谓，集群必需设置为true以配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端收到客户端最后一次心跳后等待的时间上限，超时将注销服务，默认为90秒
    lease-expiration-duration-in-seconds: 2