server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_8001_routh1             #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: http://localhost:8001          #匹配提供服务的路由地址
          predicates:
            - Path=/api/payment/get/**            #断言，路径相匹配的进行路由

        - id: payment_8001_routh2                  #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: http://localhost:8001          #匹配提供服务的路由地址
          predicates:
            - Path=/api/payment/lb/**             #断言，路径相匹配的进行路由
eureka:
  client:
    # 表示是否将自己注册到eureka-server,默认为true
    register-with-eureka: true
    # 是否从eureka-server抓取自己的注册信息，默认为true，单节点无所谓，集群必需设置为true以配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: cloud-gateway-9527
    prefer-ip-address: true