server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名称
    hostname: eureka7001
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Serve交互的地址，查询服务和注册服务都需要这依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 相互注册
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    # 关闭自我保护，保证不可用的服务即时清理
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000