server:
  port: 83
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: master:8848  #配置Nacos地址

#消费者将要去访问的微服务名称（成功注册到nacos的服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider/api



