server:
  port: 80
  tomcat:
    uri-encoding: utf-8


spring:
  application:
    name: cloud-order-feign-service

eureka:
  client:
    # 表示是否将自己注册到eureka-server,默认为true
    register-with-eureka: true
    # 是否从eureka-server抓取自己的注册信息，默认为true，单节点无所谓，集群必需设置为true以配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版

ribbon:
  ReadTimeout: 5000 #建立连接所用的时间
  ConnectTimeout: 5000 #建立连接后服务端读取可用资源所用的时间

logging:
  level:
    # feign以什么级别监控哪个接口
    com.chris.springcloud.service.PaymentFeignService: debug
