server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: consul-provider-order
  cloud:
    consul:
      host: master
      port: 8500
      discovery:
        service-name: ${spring.application.name}
